<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('nsm_principal', 'nsm_principal_principal_role_id_nsm_role_role_id', array(
             'name' => 'nsm_principal_principal_role_id_nsm_role_role_id',
             'local' => 'principal_role_id',
             'foreign' => 'role_id',
             'foreignTable' => 'nsm_role',
             ));
        $this->createForeignKey('nsm_principal', 'nsm_principal_principal_user_id_nsm_user_user_id', array(
             'name' => 'nsm_principal_principal_user_id_nsm_user_user_id',
             'local' => 'principal_user_id',
             'foreign' => 'user_id',
             'foreignTable' => 'nsm_user',
             ));
        $this->createForeignKey('nsm_principal_target', 'nsm_principal_target_pt_principal_id_nsm_principal_principal_id', array(
             'name' => 'nsm_principal_target_pt_principal_id_nsm_principal_principal_id',
             'local' => 'pt_principal_id',
             'foreign' => 'principal_id',
             'foreignTable' => 'nsm_principal',
             ));
        $this->createForeignKey('nsm_principal_target', 'nsm_principal_target_pt_target_id_nsm_target_target_id', array(
             'name' => 'nsm_principal_target_pt_target_id_nsm_target_target_id',
             'local' => 'pt_target_id',
             'foreign' => 'target_id',
             'foreignTable' => 'nsm_target',
             ));
        $this->createForeignKey('nsm_role', 'nsm_role_role_parent_nsm_role_role_id', array(
             'name' => 'nsm_role_role_parent_nsm_role_role_id',
             'local' => 'role_parent',
             'foreign' => 'role_id',
             'foreignTable' => 'nsm_role',
             ));
        $this->createForeignKey('nsm_target_value', 'nsm_target_value_tv_pt_id_nsm_principal_target_pt_id', array(
             'name' => 'nsm_target_value_tv_pt_id_nsm_principal_target_pt_id',
             'local' => 'tv_pt_id',
             'foreign' => 'pt_id',
             'foreignTable' => 'nsm_principal_target',
             ));
        $this->createForeignKey('nsm_user_preference', 'nsm_user_preference_upref_user_id_nsm_user_user_id', array(
             'name' => 'nsm_user_preference_upref_user_id_nsm_user_user_id',
             'local' => 'upref_user_id',
             'foreign' => 'user_id',
             'foreignTable' => 'nsm_user',
             ));
        $this->createForeignKey('nsm_user_role', 'nsm_user_role_usro_role_id_nsm_role_role_id', array(
             'name' => 'nsm_user_role_usro_role_id_nsm_role_role_id',
             'local' => 'usro_role_id',
             'foreign' => 'role_id',
             'foreignTable' => 'nsm_role',
             ));
        $this->createForeignKey('nsm_user_role', 'nsm_user_role_usro_user_id_nsm_user_user_id', array(
             'name' => 'nsm_user_role_usro_user_id_nsm_user_user_id',
             'local' => 'usro_user_id',
             'foreign' => 'user_id',
             'foreignTable' => 'nsm_user',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('nsm_principal', 'nsm_principal_principal_role_id_nsm_role_role_id');
        $this->dropForeignKey('nsm_principal', 'nsm_principal_principal_user_id_nsm_user_user_id');
        $this->dropForeignKey('nsm_principal_target', 'nsm_principal_target_pt_principal_id_nsm_principal_principal_id');
        $this->dropForeignKey('nsm_principal_target', 'nsm_principal_target_pt_target_id_nsm_target_target_id');
        $this->dropForeignKey('nsm_role', 'nsm_role_role_parent_nsm_role_role_id');
        $this->dropForeignKey('nsm_target_value', 'nsm_target_value_tv_pt_id_nsm_principal_target_pt_id');
        $this->dropForeignKey('nsm_user_preference', 'nsm_user_preference_upref_user_id_nsm_user_user_id');
        $this->dropForeignKey('nsm_user_role', 'nsm_user_role_usro_role_id_nsm_role_role_id');
        $this->dropForeignKey('nsm_user_role', 'nsm_user_role_usro_user_id_nsm_user_user_id');
    }
}