<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmuserpreference extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_user_preference', array(
             'upref_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => true,
             ),
             'upref_user_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'upref_val' => 
             array(
              'type' => 'string',
              'length' => 100,
              'fixed' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'upref_longval' => 
             array(
              'type' => 'blob',
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'upref_key' => 
             array(
              'type' => 'string',
              'length' => 50,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'upref_created' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'upref_modified' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'upref_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_user_preference');
    }
}