<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmtargetvalue extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_target_value', array(
             'tv_pt_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => false,
             ),
             'tv_key' => 
             array(
              'type' => 'string',
              'length' => 45,
              'fixed' => false,
              'primary' => true,
              'autoincrement' => false,
             ),
             'tv_val' => 
             array(
              'type' => 'string',
              'length' => 45,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'tv_pt_id',
              1 => 'tv_key',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_target_value');
    }
}