<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmlog extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_log', array(
             'log_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => true,
             ),
             'log_level' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'log_message' => 
             array(
              'type' => 'string',
              'length' => 4000,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'log_created' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'log_modified' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'log_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_log');
    }
}