<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmuser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_user', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => true,
             ),
             'user_account' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'length' => 18,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_lastname' => 
             array(
              'type' => 'string',
              'length' => 40,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_firstname' => 
             array(
              'type' => 'string',
              'length' => 40,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_password' => 
             array(
              'type' => 'string',
              'length' => 64,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_salt' => 
             array(
              'type' => 'string',
              'length' => 64,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_email' => 
             array(
              'type' => 'string',
              'length' => 40,
              'fixed' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_disabled' => 
             array(
              'type' => 'integer',
              'length' => 1,
              'unsigned' => 0,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_created' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'user_modified' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_user');
    }
}