<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmprincipaltarget extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_principal_target', array(
             'pt_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => true,
             ),
             'pt_principal_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'pt_target_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'pt_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_principal_target');
    }
}