<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmuserrole extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_user_role', array(
             'usro_user_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => false,
             ),
             'usro_role_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'unsigned' => 0,
              'primary' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'usro_user_id',
              1 => 'usro_role_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_user_role');
    }
}