<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnsmtarget extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('nsm_target', array(
             'target_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
             ),
             'target_name' => 
             array(
              'type' => 'string',
              'length' => 45,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'target_description' => 
             array(
              'type' => 'string',
              'length' => 100,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'target_class' => 
             array(
              'type' => 'string',
              'length' => 80,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'target_type' => 
             array(
              'type' => 'string',
              'length' => 45,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'target_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('nsm_target');
    }
}