##################################################
# file: icingaApi_client.py
# 
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     /usr/bin/wsdl2py ./icinga.wsdl
# 
##################################################
