<?php

/**
 * NsmUserPreference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class NsmUserPreference extends BaseNsmUserPreference
{

	public function setUp() {
		parent::setUp();
		
		$this->actAs('Timestampable', array (
        	'created' =>  array('name'	=> 'upref_created'),
        	'updated' =>  array('name'	=> 'upref_modified'),
        ));
	}
	
}