<?php

/**
 * Cronk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cronk extends BaseCronk {

	public function public function setUp() {
		parent::setUp();
		
		$this->hasMany('CronkCategory', array (
			'local'		=> 'ccc_cronk_id',
			'foreign'	=> 'ccc_cc_id',
			'refClass'	=> 'CronkCategoryCronk'
		));
		
        $options = array (
        	'created' =>  array('name' => 'cronk_created'),
        	'updated' =>  array('name' => 'cronk_modified'),
        );

		$this->actAs('Timestampable', $options);
	}

}