<?php

/**
 * CronkCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CronkCategory extends BaseCronkCategory {

    public function setTableDefinition() {

        parent::setTableDefinition();

        $this->index('cc_uid_UNIQUE', array(
                         'fields' => array(
                             'cc_uid'
                         ),
                         'type' => 'unique'
                     ));
    }

    public function setUp() {
        parent::setUp();

        $this->hasMany('Cronk', array(
                           'local'		=> 'ccc_cc_id',
                           'foreign'	=> 'ccc_cronk_id',
                           'refClass'	=> 'CronkCategoryCronk'
                       ));

        $options = array(
                       'created' =>  array('name' => 'cc_created'),
                       'updated' =>  array('name' => 'cc_modified'),
                   );

        $this->actAs('Timestampable', $options);
    }

}
