<?php


/**
 * Cronk
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 * @property Doctrine_Collection CronkCategory
 * @property Doctrine_Collection NsmPrincipal
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cronk extends BaseCronk {

    public function setTableDefinition() {

        parent::setTableDefinition();

        $this->index('cronk_uid_UNIQUE', array(
                         'fields' => array(
                             'cronk_uid'
                         ),
                         'type' => 'unique'
                     ));
    }

    public function setUp() {
        parent::setUp();

        $this->hasMany('CronkCategory', array(
                           'local'		=> 'ccc_cronk_id',
                           'foreign'	=> 'ccc_cc_id',
                           'refClass'	=> 'CronkCategoryCronk'
                       ));

        $this->hasMany('NsmPrincipal', array(
                           'local'		=> 'cpc_cronk_id',
                           'foreign'	=> 'cpc_principal_id',
                           'refClass'	=> 'CronkPrincipalCronk'
                       ));

        $options = array(
                       'created' =>  array('name' => 'cronk_created'),
                       'updated' =>  array('name' => 'cronk_modified'),
                   );

        $this->actAs('Timestampable', $options);
    }

}
