<?php

/**
 * LconfFiltersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LconfFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LconfFiltersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LconfFilter');
    }
}