<?php

/**
 * NsmLog
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
class NsmLog extends BaseNsmLog {

    public function setUp() {

        parent::setUp();

        $options = array(
                       'created' =>  array('name'	=> 'log_created'),
                       'updated' =>  array('name'	=> 'log_modified'),
                   );

        $this->actAs('Timestampable', $options);

    }

}