<?php

/**
 * NsmPrincipal
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class NsmPrincipal extends BaseNsmPrincipal {
    const TYPE_ROLE = 'role';
    const TYPE_USER = 'user';

    public function setUp() {
        parent::setUp();

        $this->hasMany('Cronk', array(
                           'local'		=> 'cpc_principal_id',
                           'foreign'	=> 'cpc_cronk_id',
                           'refClass'	=> 'CronkPrincipalCronk'
                       ));
    }

    /**
     * (non-PHPdoc)
     * @see Doctrine_Record::preUpdate()
     */
    public function preUpdate($event) {
        $this->updatePrincipalType();
    }

    /**
     * (non-PHPdoc)
     * @see Doctrine_Record::preInsert()
     */
    public function preInsert($event) {
        $this->updatePrincipalType();
    }

    /**
     * Checks for existing principal type and change
     * id needed
     * @throws AppKitDoctrineException2
     * @return true if no exception
     */
    private function updatePrincipalType() {

        if (in_array($this->principal_type, array(self::TYPE_ROLE, self::TYPE_USER)) === true) {
            return true;
        }

        if ($this->principal_role_id && $this->principal_user_id) {
            throw new AppKitDoctrineException('Unexpected principal condition, please check the object');
        }

        if ($this->principal_role_id) {
            $this->principal_type = self::TYPE_ROLE;
        }

        elseif($this->principal_user_id) {
            $this->principal_type = self::TYPE_USER;
        }

        return true;
    }
}
