<?php

/**
 * NsmSession
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
class NsmSession extends BaseNsmSession {

    public function get($val, $load=true) {
        $val = parent::get($val, $load);

        if (is_resource($val)) {
            return stream_get_contents($val);
        }

        return $val;
    }

    public function setUp() {

        parent::setUp();

        $options = array(
                       'created' =>  array('name'	=> 'session_created'),
                       'updated' =>  array('name'	=> 'session_modified'),
                   );

        $this->actAs('Timestampable', $options);

    }
}