<?php

/**
 * NsmUserPreference
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class NsmUserPreference extends BaseNsmUserPreference {
    public function get($val, $load=true) {
        $val = parent::get($val, $load);

        if (is_resource($val)) {
            return stream_get_contents($val);
        }

        return $val;
    }

    public function setTableDefinition() {

        parent::setTableDefinition();


    }

    public function setUp() {
        parent::setUp();

        $this->actAs('Timestampable', array(
                         'created' =>  array('name'	=> 'upref_created'),
                         'updated' =>  array('name'	=> 'upref_modified'),
                     ));
    }

}