<?php
/**
 * BaseIcingaObjects
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $object_id
 * @property integer $instance_id
 * @property integer $objecttype_id
 * @property string $name1
 * @property string $name2
 * @property integer $is_active
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIcingaObjects extends Doctrine_Record {
    public function setTableDefinition() {
        $prefix = Doctrine_Manager::getInstance()->getConnectionForComponent("IcingaObjects")->getPrefix();
        $this->setTableName($prefix.'objects');
        $this->hasColumn('id', 'integer', 4, array(
                             'type' => 'integer',
                             'length' => 4,
                             'fixed' => false,
                             'unsigned' => false,
                             'primary' => true,
                             'autoincrement' => true,
                         ));
        $this->hasColumn('instance_id', 'integer', 2, array(
                             'type' => 'integer',
                             'length' => 2,
                             'fixed' => false,
                             'unsigned' => false,
                             'primary' => false,
                             'default' => '0',
                             'notnull' => true,
                             'autoincrement' => false,
                         ));
        $this->hasColumn('objecttype_id', 'integer', 2, array(
                             'type' => 'integer',
                             'length' => 2,
                             'fixed' => false,
                             'unsigned' => false,
                             'primary' => false,
                             'default' => '0',
                             'notnull' => true,
                             'autoincrement' => false,
                         ));
        $this->hasColumn('name1', 'string', 128, array(
                             'type' => 'string',
                             'length' => 128,
                             'fixed' => false,
                             'unsigned' => false,
                             'primary' => false,
                             'default' => '',
                             'notnull' => true,
                             'autoincrement' => false,
                         ));
        $this->hasColumn('name2', 'string', 128, array(
                             'type' => 'string',
                             'length' => 128,
                             'fixed' => false,
                             'unsigned' => false,
                             'primary' => false,
                             'notnull' => false,
                             'autoincrement' => false,
                         ));
        $this->hasColumn('is_active', 'integer', 2, array(
                             'type' => 'integer',
                             'length' => 2,
                             'fixed' => false,
                             'unsigned' => false,
                             'primary' => false,
                             'default' => '0',
                             'notnull' => true,
                             'autoincrement' => false,
                         ));
    }

    public function setUp() {
        $this->hasOne('IcingaInstances as instance', array(
            'local' => 'instance_id',
            'foreign' => 'id'
        ));
        
        // Weak binding to derived objects
        
        $this->hasOne('IcingaHosts as host', array(
            'local' => 'id',
            'foreign' => 'host_object_id'
        ));
        $this->hasOne('IcingaServices as service', array(
            'local' => 'id',
            'foreign' => 'service_object_id'
        ));
        $this->hasOne('IcingaServicegroups as servicegroup', array(
            'local' => 'id',
            'foreign' => 'servicegroup_object_id' 
        )); 
        $this->hasOne('IcingaHostgroups as hostgroup', array(
            'local' => 'id',
            'foreign' => 'hostgroup_object_id' 
        )); 
        $this->hasOne('IcingaContactgroups as contactgroup', array(
            'local' => 'id',
            'foreign' => 'contactgroup_object_id' 
        )); 
        $this->hasOne('IcingaTimeperiod as timeperiod', array(
            'local' => 'id',
            'foreign' => 'timeperiod_object_id'
        )); 
        $this->hasOne('IcingaNotifications as notification', array(
            'local' => 'id',
            'foreign' => 'notification_object_id'
        ));
        parent::setUp();

    }
}
