<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/config/action_filters.xml
// Generated by: AgaviFilterConfigHandler
// Date: 2009-04-20T08:08:55+0000

$filter = new AgaviExecutionTimeFilter();
$filter->initialize($this->context, array (
  'comment' => true,
  'output_types' => 
  array (
    0 => 'html',
  ),
));
$filters[] = $filter;

?>