<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Widgets/AddHeaderData.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:08:55+0000



?>