<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2009-04-20T08:08:55+0000

return array (
  'ICINGAAppKitBaseAction' => '/data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/lib/action/NETWAYSAppKitBaseAction.class.php',
  'ICINGAAppKitBaseModel' => '/data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/lib/model/NETWAYSAppKitBaseModel.class.php',
  'ICINGAAppKitBaseView' => '/data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/lib/view/NETWAYSAppKitBaseView.class.php',
);

?>