<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2009-04-20T08:08:55+0000

return array (
)

?>