<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/config/databases.xml
// Generated by: AgaviDatabaseConfigHandler
// Date: 2009-04-20T08:27:30+0000

$database = new AgaviDoctrineDatabase();
$this->databases['appkit_default'] = $database;
$database->initialize($this, array (
  'dsn' => 'mysql://ng_dev:ng_dev@127.0.0.1:3307/icinga',
  'username' => 'ng_dev',
  'password' => 'ng_dev',
  'charset' => 'utf8',
  'manager_attributes' => 
  array (
    'MODEL_LOADING' => 'CONSERVATIVE',
  ),
  'load_models' => '/data/mhein/workspace-icinga/icinga-web/lib/appkit/database/models',
));
$this->defaultDatabaseName = 'appkit_default';

?>