<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Admin/Groups/Edit.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:21:05+0000

if($method == 'read') {
${'_validator_user_id'} = new AgaviRegexValidator();
${'_validator_user_id'}->initialize($this->getContext(), array (
  'match' => true,
  'severity' => 'error',
  'required' => false,
  'class' => 'regex',
  'name' => 'user_id',
  'pattern' => '@^\\d+|new$@',
), array (
  0 => 'id',
), array (
));
${'validationManager'}->addChild(${'_validator_user_id'});
}
if($method == 'write') {
${'_validator_user_id'} = new AgaviRegexValidator();
${'_validator_user_id'}->initialize($this->getContext(), array (
  'match' => true,
  'severity' => 'error',
  'required' => false,
  'class' => 'regex',
  'name' => 'user_id',
  'pattern' => '@^\\d+|new$@',
), array (
  0 => 'id',
), array (
));
${'validationManager'}->addChild(${'_validator_user_id'});
${'_validator_role_name'} = new AgaviStringValidator();
${'_validator_role_name'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'role_name',
  'max' => '40',
), array (
  0 => 'role_name',
), array (
  'min' => 'The rolename you supplied is fewer than 1 characters long.',
  'max' => 'Your rolename is too long',
  '' => 'You have to supply a rolename!',
));
${'validationManager'}->addChild(${'_validator_role_name'});
${'_validator_role_description'} = new AgaviStringValidator();
${'_validator_role_description'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'role_description',
  'max' => '255',
), array (
  0 => 'role_description',
), array (
  'min' => 'The description you supplied is fewer than 1 characters long.',
  'max' => 'Your description is too long',
  '' => 'You have to supply a description!',
));
${'validationManager'}->addChild(${'_validator_role_description'});
${'_validator_49ec30713ab462.30149518'} = new AgaviOroperatorValidator();
${'_validator_49ec30713ab462.30149518'}->initialize($this->getContext(), array (
  'break' => true,
  'severity' => 'error',
  'required' => true,
  'class' => 'or',
  'name' => '49ec30713ab462.30149518',
), array (
), array (
));
${'validationManager'}->addChild(${'_validator_49ec30713ab462.30149518'});
${'_validator_49ec30713ade88.04216145'} = new AgaviNumberValidator();
${'_validator_49ec30713ade88.04216145'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => '49ec30713ade88.04216145',
), array (
  0 => 'role_disabled',
), array (
));
${'_validator_49ec30713ab462.30149518'}->addChild(${'_validator_49ec30713ade88.04216145'});
${'_validator_49ec30713b0ae1.89028447'} = new AgaviSetValidator();
${'_validator_49ec30713b0ae1.89028447'}->initialize($this->getContext(), array (
  'severity' => 'error',
  'required' => false,
  'class' => 'set',
  'name' => '49ec30713b0ae1.89028447',
  'export' => 'role_disabled',
  'value' => '0',
), array (
), array (
));
${'_validator_49ec30713ab462.30149518'}->addChild(${'_validator_49ec30713b0ae1.89028447'});
}

?>