<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Admin/Users/Index.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:09:58+0000

if($method == 'read') {
${'_validator_doctrine_pager_offset'} = new AgaviNumberValidator();
${'_validator_doctrine_pager_offset'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'doctrine_pager_offset',
), array (
  0 => 'page_offset',
), array (
));
${'validationManager'}->addChild(${'_validator_doctrine_pager_offset'});
${'_validator_49ec2dd6877452.94038644'} = new AgaviAndoperatorValidator();
${'_validator_49ec2dd6877452.94038644'}->initialize($this->getContext(), array (
  'break' => true,
  'severity' => 'error',
  'required' => false,
  'class' => 'and',
  'name' => '49ec2dd6877452.94038644',
), array (
), array (
));
${'validationManager'}->addChild(${'_validator_49ec2dd6877452.94038644'});
${'_validator_user_id'} = new AgaviNumberValidator();
${'_validator_user_id'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'user_id',
), array (
  0 => 'id',
), array (
));
${'_validator_49ec2dd6877452.94038644'}->addChild(${'_validator_user_id'});
${'_validator_toggle_activity'} = new AgaviNumberValidator();
${'_validator_toggle_activity'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'toggle_activity',
), array (
  0 => 'toggleActivity',
), array (
));
${'_validator_49ec2dd6877452.94038644'}->addChild(${'_validator_toggle_activity'});
}

?>