<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/config/logging.xml
// Generated by: AgaviLoggingConfigHandler
// Date: 2009-04-20T08:08:34+0000

${'_layout_DateTimeLayout'} = new AgaviTimestampLoggerLayout();
${'_layout_DateTimeLayout'}->initialize($this->context, array (
));
${'_layout_PassThru'} = new AgaviPassthruLoggerLayout();
${'_layout_PassThru'}->initialize($this->context, array (
));
${'_appender_AppKitLogAppender'} = new AppKitDoctrineLoggerAppender();
${'_appender_AppKitLogAppender'}->initialize($this->context, array (
));
${'_appender_AppKitLogAppender'}->setLayout(${'_layout_PassThru'});
${'_appender_AppKitQueueAppender'} = new AppKitMessageQueueLoggerAppender();
${'_appender_AppKitQueueAppender'}->initialize($this->context, array (
));
${'_appender_AppKitQueueAppender'}->setLayout(${'_layout_DateTimeLayout'});
${'_logger_appkit_default'} = new AgaviLogger();
${'_logger_appkit_default'}->setAppender('AppKitLogAppender', ${'_appender_AppKitLogAppender'});
${'_logger_appkit_default'}->setAppender('AppKitQueueAppender', ${'_appender_AppKitQueueAppender'});
${'_logger_appkit_default'}->setLevel(AgaviLogger::ALL);
$this->setLogger('appkit_default', ${'_logger_appkit_default'});
$this->setDefaultLoggerName('appkit_default');

?>