<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Login.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:09:48+0000

if($method == 'write') {
${'_validator_username_length'} = new AgaviStringValidator();
${'_validator_username_length'}->initialize($this->getContext(), array (
  'min' => '3',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'username_length',
  'max' => '10',
), array (
  0 => 'username',
), array (
  '' => 'Please provide a username',
  'max' => 'Username is too long',
));
${'validationManager'}->addChild(${'_validator_username_length'});
${'_validator_password_length'} = new AgaviStringValidator();
${'_validator_password_length'}->initialize($this->getContext(), array (
  'min' => '3',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'password_length',
  'max' => '80',
), array (
  0 => 'password',
), array (
  '' => 'Please provide a password',
  'max' => 'Password is too long',
));
${'validationManager'}->addChild(${'_validator_password_length'});
}

?>