<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/config/output_types.xml
// Generated by: AgaviOutputTypeConfigHandler
// Date: 2009-04-20T08:08:55+0000

$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/html; charset=UTF-8',
  ),
), 'html', array (
  'php' => 
  array (
    'class' => 'AgaviPhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
      'assigns' => 
      array (
        'routing' => 'ro',
        'request' => 'rq',
        'controller' => 'ct',
        'user' => 'us',
        'translation_manager' => 'tm',
        'request_data' => 'rd',
      ),
      'var_name' => 't',
    ),
  ),
), 'php', array (
  'NETWAYSWireFrame' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
      'decorator' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
          'directory' => '/data/mhein/workspace-icinga/icinga-web/app/templates',
          'template' => 'NETWAYSWireFrameMaster',
        ),
        'renderer' => NULL,
        'slots' => 
        array (
          'additional_header_data' => 
          array (
            'action' => 'Widgets.AddHeaderData',
            'module' => 'AppKit',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
          'navigation_top' => 
          array (
            'action' => 'Widgets.ShowNavigation',
            'module' => 'AppKit',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
              'type' => 'top',
            ),
          ),
          'navigation_left' => 
          array (
            'action' => 'Widgets.ShowNavigation',
            'module' => 'AppKit',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
              'type' => 'left',
            ),
          ),
          'error_frame' => 
          array (
            'action' => 'Widgets.ShowErrors',
            'module' => 'AppKit',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
              'type' => '7',
            ),
          ),
          'footer' => 
          array (
            'action' => 'Widgets.ShowFooter',
            'module' => 'AppKit',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
  'simple' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
  'slot' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'NETWAYSWireFrame', NULL);
$this->outputTypes['html'] = $ot;
$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Pragma' => NULL,
    'Set-Cookie' => NULL,
  ),
), 'image', array (
), NULL, array (
), NULL, NULL);
$this->outputTypes['image'] = $ot;
$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/xml; charset=UTF-8',
  ),
), 'xml', array (
), NULL, array (
), NULL, NULL);
$this->outputTypes['xml'] = $ot;
$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/x-json; charset=UTF-8',
  ),
), 'json', array (
), NULL, array (
), NULL, NULL);
$this->outputTypes['json'] = $ot;
$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
), 'ajax', array (
  'php' => 
  array (
    'class' => 'AgaviPhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
      'assigns' => 
      array (
        'routing' => 'ro',
        'request' => 'rq',
        'controller' => 'ct',
        'user' => 'us',
        'translation_manager' => 'tm',
        'request_data' => 'rd',
      ),
      'var_name' => 't',
    ),
  ),
), 'php', array (
  'simple' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'simple', NULL);
$this->outputTypes['ajax'] = $ot;
$this->defaultOutputType = 'html';

?>