<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/config/rbac_definitions.xml
// Generated by: AgaviRbacDefinitionConfigHandler
// Date: 2009-04-20T08:08:55+0000

return array (
  'appkit_admin' => 
  array (
    'parent' => 'appkit_user',
    'permissions' => 
    array (
      0 => 'appkit.admin',
      1 => 'appkit.admin.users',
      2 => 'appkit.admin.groups',
    ),
  ),
  'appkit_user' => 
  array (
    'parent' => 'grapher_admin',
    'permissions' => 
    array (
      0 => 'appkit.user.dummy',
    ),
  ),
  'grapher_admin' => 
  array (
    'parent' => 'grapher_user',
    'permissions' => 
    array (
      0 => 'grapher.admin.access',
      1 => 'grapher.admin',
    ),
  ),
  'grapher_user' => 
  array (
    'parent' => 'guest',
    'permissions' => 
    array (
      0 => 'grapher.access',
    ),
  ),
  'guest' => 
  array (
    'parent' => NULL,
    'permissions' => 
    array (
      0 => 'appkit.access',
    ),
  ),
);

?>