<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/config/settings.xml
// Generated by: AgaviSettingConfigHandler
// Date: 2009-04-20T08:08:33+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'AppKit',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'AppKit',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'AppKit',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'AppKit',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'AppKit',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'AppKit',
  'actions.login_action' => 'Login',
  'core.app_name' => 'NETWAYS',
  'core.available' => true,
  'core.debug' => false,
  'core.use_database' => true,
  'core.use_logging' => true,
  'core.use_security' => true,
  'core.use_translation' => false,
  'de.netways.appkit.php_settings' => 
  array (
    'session.gc_probability' => '3',
    'session.gc_divisor' => '100',
    'session.gc_maxlifetime' => '86400',
  ),
  'de.netways.appkit.autoloader.paths' => 
  array (
    0 => '/data/mhein/workspace-icinga/icinga-web/lib/appkit',
  ),
  'de.netways.appkit.autoloader.prefixes' => 
  array (
    0 => 'AppKit',
  ),
  'de.netways.appkit.doctrine_path' => '../lib/doctrine/lib',
  'de.netways.appkit.doctrine_model_path' => '/data/mhein/workspace-icinga/icinga-web/lib/appkit/database/models',
  'de.netways.appkit.image_path' => '/data/mhein/workspace-icinga/icinga-web/pub/images',
  'de.netways.appkit.menu_extender' => '',
  'de.netways.appkit.include_styles' => 
  array (
    0 => '/styles/WireFrameDefault.css',
    1 => '/styles/WireFrameStructural.css',
    2 => '/styles/Grapher.css',
    3 => '/js/yui/build/fonts/fonts-min.css',
    4 => '/js/yui/build/menu/assets/skins/sam/menu.css',
    5 => '/js/yui/build/tabview/assets/skins/sam/tabview.css',
    6 => '/js/yui/build/autocomplete/assets/skins/sam/autocomplete.css',
    7 => '/js/yui/build/container/assets/skins/sam/container.css',
    8 => '/js/yui/build/button/assets/skins/sam/button.css',
    9 => '/js/yui/build/resize/assets/skins/sam/resize.css',
    10 => '/js/yui/build/calendar/assets/skins/sam/calendar.css',
    11 => '/styles/WireFrameYUI.css',
    12 => '/js/gc-prettify/prettify.css',
  ),
  'de.netways.appkit.meta_tags' => 
  array (
    'author' => '(c) 2009 ICINGA - www.icinga.org',
    'robots' => 'noindex',
  ),
  'de.netways.appkit.include_javascript' => 
  array (
    0 => '/js/yui/build/yahoo/yahoo-min.js',
    1 => '/js/yui/build/event/event-min.js',
    2 => '/js/yui/build/yahoo-dom-event/yahoo-dom-event.js',
    3 => '/js/yui/build/container/container-min.js',
    4 => '/js/yui/build/datasource/datasource-min.js',
    5 => '/js/yui/build/get/get-min.js',
    6 => '/js/yui/build/element/element-beta-min.js',
    7 => '/js/yui/build/connection/connection-min.js',
    8 => '/js/yui/build/json/json-min.js',
    9 => '/js/yui/build/animation/animation-min.js',
    10 => '/js/yui/build/autocomplete/autocomplete-min.js',
    11 => '/js/yui/build/menu/menu-min.js',
    12 => '/js/yui/build/tabview/tabview-min.js',
    13 => '/js/yui/build/tabview/tabview-min.js',
    14 => '/js/yui/build/dragdrop/dragdrop-min.js',
    15 => '/js/yui/build/button/button-min.js',
    16 => '/js/yui/build/calendar/calendar-min.js',
    17 => '/js/yui/build/resize/resize-min.js',
    18 => '/js/yui/build/cookie/cookie-min.js',
    19 => '/js/jquery/jquery-1.3.1.min.js',
    20 => '/js/appkit/AppKit.js',
    21 => '/js/appkit/Grapher.js',
    22 => '/js/appkit/dump.js',
    23 => '/js/swfobject/swfobject.js',
    24 => '/js/gc-prettify/prettify.js',
  ),
  'de.netways.appkit.pager.default_items' => '20',
  'de.netways.appkit.factories' => 
  array (
    'MessageQueue' => 
    array (
      'class' => 'AppKitMessageQueue',
    ),
    'AuthProvider' => 
    array (
      'class' => 'AppKitAuthProviderDatabase',
    ),
  ),
  'de.netways.appkit.ajax.ac.prefix' => 'de.netways.appkit.ajax.ac.types',
  'de.netways.appkit.ajax.ac.types' => '',
  'de.netways.appkit.ajax.fs.prefix' => 'de.netways.appkit.ajax.fs.sources',
  'exception.default_template' => '/data/mhein/workspace-icinga/icinga-web/lib/agavi/src/exception/templates/shiny.php',
  'exception.templates.console' => '/data/mhein/workspace-icinga/icinga-web/lib/agavi/src/exception/templates/plaintext.php',
));

?>