<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Widgets/ShowImage.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:08:56+0000

${'_validator_image_name'} = new AgaviStringValidator();
${'_validator_image_name'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'image_name',
  'max' => '255',
), array (
  0 => 'image',
), array (
  '' => 'The imagename is too long',
));
${'validationManager'}->addChild(${'_validator_image_name'});

?>