<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Widgets/ShowErrors.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:08:55+0000

${'_validator_type_value'} = new AgaviStringValidator();
${'_validator_type_value'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'type_value',
  'max' => '255',
), array (
  0 => 'type',
), array (
  '' => 'The imagename is too long',
));
${'validationManager'}->addChild(${'_validator_type_value'});

?>