<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/mhein/workspace-icinga/icinga-web/app/modules/AppKit/validate/Admin/ViewLogs.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2009-04-20T08:10:03+0000

if($method == 'read') {
${'_validator_doctrine_pager_offset'} = new AgaviNumberValidator();
${'_validator_doctrine_pager_offset'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'doctrine_pager_offset',
), array (
  0 => 'page_offset',
), array (
));
${'validationManager'}->addChild(${'_validator_doctrine_pager_offset'});
}

?>