<?php

/**
 * Data file for Antarctica/Vostok timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 02/14/2009 18:36:26
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id: Antarctica_47_Vostok.php 3838 2009-02-14 18:42:45Z david $
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'VOST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -380073600,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'VOST',
    'offset' => 21600,
    'startYear' => 1958,
  ),
  'name' => 'Antarctica/Vostok',
);

?>