<?php

/**
 * Data file for Asia/Aden timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 02/14/2009 18:36:26
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id: Asia_47_Aden.php 3838 2009-02-14 18:42:45Z david $
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -631162848,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AST',
    'offset' => 10800,
    'startYear' => 1950,
  ),
  'name' => 'Asia/Aden',
);

?>