<?php

/**
 * Data file for Asia/Muscat timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/29/2009 04:12:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id: Asia_47_Muscat.php 4045 2009-04-29 04:14:08Z david $
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'GST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1577937260,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GST',
    'offset' => 14400,
    'startYear' => 1920,
  ),
  'name' => 'Asia/Muscat',
);

?>