<?php

/**
 * Data file for Etc/GMT+5 timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/29/2009 04:12:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id: Etc_47_GMT_43_5.php 4045 2009-04-29 04:14:08Z david $
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT+5',
    'offset' => -18000,
    'startYear' => -2147483647,
  ),
  'name' => 'Etc/GMT+5',
);

?>