<?php

/**
 * IcingaServicedependenciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServicedependenciesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServicedependenciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServicedependencies');
    }
}