<?php

/**
 * IcingaServicegroupMembersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServicegroupMembersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServicegroupMembersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServicegroupMembers');
    }
}