<?php

/**
 * IcingaHostescalationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostescalationsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostescalationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostescalations');
    }
}