<?php

/**
 * IcingaHostgroupsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostgroupsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostgroupsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaHostgroups');
    }
}