<?php

/**
 * IcingaCustomvariablestatusTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaCustomvariablestatusTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaCustomvariablestatusTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaCustomvariablestatus');
    }
}