<?php

/**
 * IcingaScheduleddowntimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaScheduleddowntimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaScheduleddowntimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaScheduleddowntime');
    }
}