<?php

/**
 * IcingaDbversionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaDbversionTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaDbversionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaDbversion');
    }
}