<?php

/**
 * IcingaHostdependenciesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostdependenciesTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostdependenciesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaHostdependencies');
    }
}