<?php

/**
 * IcingaNotificationsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaNotificationsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaNotificationsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaNotifications');
    }
}