<?php

/**
 * IcingaConninfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaConninfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaConninfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaConninfo');
    }
}