<?php

/**
 * IcingaHostContactgroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostContactgroupsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostContactgroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostContactgroups');
    }
}