<?php

/**
 * IcingaContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaContacts');
    }
}