<?php

/**
 * IcingaServiceescalationContactgroupsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServiceescalationContactgroupsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServiceescalationContactgroupsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaServiceescalationContactgroups');
    }
}