<?php

/**
 * IcingaHostContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostContactsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostContacts');
    }
}