<?php

/**
 * IcingaServiceescalationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServiceescalationsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServiceescalationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServiceescalations');
    }
}