<?php

/**
 * IcingaHostescalationContactgroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostescalationContactgroupsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostescalationContactgroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostescalationContactgroups');
    }
}