<?php

/**
 * IcingaCommenthistoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaCommenthistoryTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaCommenthistoryTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaCommenthistory');
    }
}