<?php

/**
 * IcingaHosts
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IcingaHosts extends BaseIcingaHosts {
    public static $STATE_UP = 0;
    public static $STATE_DOWN = 1;
    public static $STATE_UNREACHABLE = 2;
}
