<?php

/**
 * IcingaCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaCommentsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaComments');
    }
}