<?php

/**
 * IcingaProcesseventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaProcesseventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaProcesseventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaProcessevents');
    }
}