<?php

/**
 * IcingaCommandsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaCommandsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaCommandsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaCommands');
    }
}