<?php

/**
 * IcingaExternalcommandsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaExternalcommandsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaExternalcommandsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaExternalcommands');
    }
}