<?php

/**
 * IcingaServiceContactgroupsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServiceContactgroupsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServiceContactgroupsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaServiceContactgroups');
    }
}