<?php

/**
 * IcingaContactgroupMembersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactgroupMembersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactgroupMembersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaContactgroupMembers');
    }
}