<?php

/**
 * IcingaServices
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IcingaServices extends BaseIcingaServices {
    public static $STATE_OK = 0;
    public static $STATE_WARNING = 1;
    public static $STATE_CRITICAL = 2;
    public static $STATE_UNKNOWN = 3;
}
