<?php

/**
 * IcingaServicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServicesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServices');
    }
}