<?php

/**
 * IcingaDowntimehistoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaDowntimehistoryTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaDowntimehistoryTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaDowntimehistory');
    }
}