<?php

/**
 * IcingaEventhandlersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaEventhandlersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaEventhandlersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaEventhandlers');
    }
}