<?php

/**
 * IcingaServicegroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServicegroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServicegroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServicegroups');
    }
}