<?php

/**
 * IcingaRuntimevariablesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaRuntimevariablesTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaRuntimevariablesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaRuntimevariables');
    }
}