<?php

/**
 * IcingaInstancesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaInstancesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaInstancesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaInstances');
    }
}