<?php

/**
 * IcingaContactgroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactgroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactgroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaContactgroups');
    }
}