<?php

/**
 * IcingaServiceContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServiceContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServiceContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServiceContacts');
    }
}