<?php

/**
 * IcingaContactnotificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactnotificationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactnotificationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaContactnotifications');
    }
}