<?php

/**
 * IcingaConfigfilevariablesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaConfigfilevariablesTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaConfigfilevariablesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaConfigfilevariables');
    }
}