<?php

/**
 * IcingaAcknowledgementsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaAcknowledgementsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaAcknowledgementsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaAcknowledgements');
    }
}