<?php

/**
 * IcingaHostchecksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostchecksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostchecksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostchecks');
    }
}