<?php

/**
 * IcingaHostgroupMembersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostgroupMembersTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostgroupMembersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostgroupMembers');
    }
}