<?php

/**
 * IcingaHosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IcingaHosts extends BaseIcingaHosts
{
	public function __get($method)  {
		switch($method) {
			case  'contacts':
				echo $method;
				die();
				break;
			case 'contactgroups':
				break;
		}
		return parent::__get($method);
	} 	
	
}
