<?php

/**
 * IcingaTimeperiodsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaTimeperiodsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaTimeperiodsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaTimeperiods');
    }
}