<?php

/**
 * IcingaContactnotificationmethodsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactnotificationmethodsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactnotificationmethodsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaContactnotificationmethods');
    }
}