<?php

/**
 * IcingaObjectsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaObjectsTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaObjectsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaObjects');
    }
}