<?php

/**
 * IcingaTimedeventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaTimedeventsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaTimedeventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaTimedevents');
    }
}