<?php

/**
 * IcingaHoststatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHoststatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHoststatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHoststatus');
    }
}