<?php

/**
 * IcingaServicestatusTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServicestatusTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServicestatusTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaServicestatus');
    }
}