<?php

/**
 * IcingaContactstatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactstatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactstatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaContactstatus');
    }
}