<?php

/**
 * IcingaStatehistoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaStatehistoryTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaStatehistoryTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaStatehistory');
    }
}