<?php

/**
 * IcingaServiceescalationContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServiceescalationContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServiceescalationContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServiceescalationContacts');
    }
}