<?php

/**
 * IcingaProgramstatusTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaProgramstatusTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaProgramstatusTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaProgramstatus');
    }
}