<?php

/**
 * IcingaLogentriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaLogentriesTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaLogentriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaLogentries');
    }
}