<?php

/**
 * IcingaContactNotificationcommandsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaContactNotificationcommandsTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaContactNotificationcommandsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaContactNotificationcommands');
    }
}