<?php

/**
 * IcingaTimedeventqueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaTimedeventqueueTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaTimedeventqueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaTimedeventqueue');
    }
}