<?php

/**
 * IcingaConfigfilesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaConfigfilesTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaConfigfilesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaConfigfiles');
    }
}