<?php

/**
 * IcingaHostsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostsTable extends Icinga_Doctrine_Table
{
   
   /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostsTable
     */
    public static function getInstance()
    {
       return Doctrine_Core::getTable('IcingaHosts');
    }
}
