<?php

/**
 * IcingaHostParenthostsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostParenthostsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostParenthostsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostParenthosts');
    }
}