<?php

/**
 * IcingaFlappinghistoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaFlappinghistoryTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaFlappinghistoryTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaFlappinghistory');
    }
}