<?php

/**
 * IcingaHostescalationContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostescalationContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostescalationContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaHostescalationContacts');
    }
}