<?php

/**
 * IcingaCustomvariablesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaCustomvariablesTable extends Icinga_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaCustomvariablesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaCustomvariables');
    }
}