<?php

/**
 * IcingaHostchecksTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaHostchecksTable extends Icinga_Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaHostchecksTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('IcingaHostchecks');
    }
}