<?php

/**
 * IcingaServicechecksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcingaServicechecksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IcingaServicechecksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IcingaServicechecks');
    }
}